const fs = require('fs');

// Helper to generate random reviews
const reviewTexts = [
    "Отличное приложение, пользуюсь каждый день!",
    "Работает стабильно, без нареканий.",
    "Очень удобный интерфейс, рекомендую.",
    "Лучшее в своём классе, однозначно!",
    "Разработчики молодцы, постоянно обновляют.",
    "Давно пользуюсь, очень доволен.",
    "Быстро, удобно, без лишнего.",
    "Всё работает как часы, спасибо!",
    "Отличная замена аналогам.",
    "Пользуюсь уже несколько лет — огонь!",
];
const reviewAuthors = [
    "Иван К.", "Мария П.", "Александр Н.", "Ольга С.", "Дмитрий Л.",
    "Анна В.", "Сергей М.", "Елена Ф.", "Максим Р.", "Наталья Б.",
    "Алексей Д.", "Юлия Г.", "Андрей И.", "Татьяна Ж.", "Кирилл Ю.",
];
function randReviews(count = 3) {
    const reviews = [];
    for (let i = 0; i < count; i++) {
        reviews.push({
            id: `rev_${Date.now()}_${i}_${Math.floor(Math.random()*999)}`,
            author: reviewAuthors[Math.floor(Math.random() * reviewAuthors.length)],
            text: reviewTexts[Math.floor(Math.random() * reviewTexts.length)],
            rating: Math.floor(Math.random() * 2) + 4,
            date: "Сегодня"
        });
    }
    return reviews;
}

// Real app icons from well-known CDNs
const newApps = {
    // ========== STREAMING & MEDIA ==========
    "netflix": {
        title: "Netflix",
        aliases: ["netflix", "нетфликс", "нефликс"],
        developer: "Netflix, Inc.",
        category: "Медиа",
        rating: "4.4",
        reviewsCount: "12 млн",
        downloads: "1 млрд +",
        size: "85.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/TBRwjS_qfJCSj1m7zZB93FnpJM5fSpMA_wUlFDLxWAb45T9RmwBvQd5cWR5viJJOhkI",
        description: "Смотрите фильмы, сериалы и документальное кино из каталога Netflix в любое время и в любом месте.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "spotify": {
        title: "Spotify: музыка и подкасты",
        aliases: ["spotify", "спотифай", "спотифи"],
        developer: "Spotify AB",
        category: "Медиа",
        rating: "4.3",
        reviewsCount: "8 млн",
        downloads: "1 млрд +",
        size: "30.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WTZR8HQLyuQN7N_Y3sO0XgbZT_3Q",
        description: "Spotify — это крупнейший в мире стриминговый музыкальный сервис. Более 100 миллионов треков, подкасты и аудиокниги.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "disneyplus": {
        title: "Disney+",
        aliases: ["disney", "disney+", "диснейплюс", "дисней"],
        developer: "Disney",
        category: "Медиа",
        rating: "4.5",
        reviewsCount: "3 млн",
        downloads: "500 млн +",
        size: "55.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/xoGGYH2LgLibLDBoxMg-ZE16b-TNgx--WtRBMkdIdp6KF_9oKKKZA2vSS89YPCX3SA",
        description: "Disney+: фильмы и сериалы Marvel, «Звёздных войн», Disney, Pixar и National Geographic.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "hbomax": {
        title: "Max: сериалы, фильмы и кино",
        aliases: ["hbo", "hbo max", "max", "хбо макс", "макс"],
        developer: "WarnerMedia",
        category: "Медиа",
        rating: "4.2",
        reviewsCount: "1.5 млн",
        downloads: "100 млн +",
        size: "48.0 MB",
        age: "16+",
        icon: "https://play-lh.googleusercontent.com/1iyX7VdQ7MiRPn4M_XGK4qvPnBJ7ZORtC4IM22LlvBvW2Gb5vlkKM8OGthBOtALRTg",
        description: "Max — это HBO, Warner Bros., DC и многое другое в одном сервисе.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== SOCIAL MEDIA ==========
    "tinder": {
        title: "Tinder: знакомства и общение",
        aliases: ["tinder", "тиндер"],
        developer: "Match Group, LLC",
        category: "Социальные сети",
        rating: "3.9",
        reviewsCount: "4 млн",
        downloads: "500 млн +",
        size: "90.0 MB",
        age: "17+",
        icon: "https://play-lh.googleusercontent.com/MEyMULMVJaXCixnrrMU7dvkQRHhWWCGXCN7fO56YgXjnMnr1m7aVNFOPHQhkLnPEqg",
        description: "Tinder — это самое популярное приложение для знакомств в мире.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "instagram": {
        title: "Instagram",
        aliases: ["instagram", "инстаграм", "инста"],
        developer: "Instagram",
        category: "Социальные сети",
        rating: "4.1",
        reviewsCount: "120 млн",
        downloads: "5 млрд +",
        size: "65.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/VRMWkE5p3CkWhJs6nv-9ZsLAs1QOWhQ62MToUAfhjFTnxrnP6n1fPqrtF55-cidk_A",
        description: "Instagram — это визуальная платформа для обмена фото и видео, Stories и Reels.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "facebook": {
        title: "Facebook",
        aliases: ["facebook", "фейсбук", "фб"],
        developer: "Meta Platforms, Inc.",
        category: "Социальные сети",
        rating: "3.8",
        reviewsCount: "150 млн",
        downloads: "5 млрд +",
        size: "75.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/KSuaRLiI_FlDP8cM4MzJ23ml3og5Vxj63mvqUIzkH-uWefYWAFHpTf2cBrSHJA2K_A",
        description: "Facebook — это социальная сеть для общения с друзьями, семьёй и людьми по всему миру.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "threads": {
        title: "Threads",
        aliases: ["threads", "тредс"],
        developer: "Instagram",
        category: "Социальные сети",
        rating: "4.0",
        reviewsCount: "1.2 млн",
        downloads: "200 млн +",
        size: "50.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/GZCmqETiG4OqrLHD5c5BRr1gm3boCBJGX5MKmSFWd9b8m9x5-EJicBSO31AJGizuqA",
        description: "Threads — это приложение для обмена текстовыми сообщениями от Instagram.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "xtwitter": {
        title: "X (Twitter)",
        aliases: ["x", "twitter", "твиттер", "икс"],
        developer: "X Corp.",
        category: "Социальные сети",
        rating: "4.0",
        reviewsCount: "25 млн",
        downloads: "1 млрд +",
        size: "40.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/AJ0DI3KiYFGKIZvJE9JuJNJDGHJPJlFLbGEPnkFnm2kkL1KK2kCkf-D_M1X2c50Yjg",
        description: "X (ранее Twitter) — это место, где происходит всё и сразу: новости, обсуждения, тренды.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "linkedin": {
        title: "LinkedIn: работа и карьера",
        aliases: ["linkedin", "линкедин"],
        developer: "LinkedIn Corporation",
        category: "Социальные сети",
        rating: "4.2",
        reviewsCount: "5 млн",
        downloads: "500 млн +",
        size: "85.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/qr6SygFGUnaXF_vu5HSSbFAEjWdAQ-Cb9GDPW6N6ZJFahzCuOBn2T1D3Wt2yNUMcg",
        description: "LinkedIn — это профессиональная социальная сеть для поиска работы и деловых контактов.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "pinterest": {
        title: "Pinterest",
        aliases: ["pinterest", "пинтерест"],
        developer: "Pinterest, Inc.",
        category: "Социальные сети",
        rating: "4.4",
        reviewsCount: "4 млн",
        downloads: "500 млн +",
        size: "45.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/NIWgfgH9dNi5sXnrF3QPYD6A2C0sMPh3sFgaGJJtXlH0B7Y9p06AiRxdD4Ga9pHNw",
        description: "Pinterest — это визуальная доска вдохновения для идей по дому, моде, рецептам и многому другому.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "snapchat": {
        title: "Snapchat",
        aliases: ["snapchat", "снэпчат", "снапчат"],
        developer: "Snap Inc.",
        category: "Социальные сети",
        rating: "4.0",
        reviewsCount: "15 млн",
        downloads: "1 млрд +",
        size: "90.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/NUh2xL4vLbQD3YbBrNdE2OTlr4i2Tul3OVqYD1bX9bUbz0RFe0YCwcbJy9y_R0v-rAj",
        description: "Snapchat — это камера и мессенджер с исчезающими сообщениями, Stories и AR-фильтрами.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== AI APPS ==========
    "chatgpt": {
        title: "ChatGPT",
        aliases: ["chatgpt", "чатгпт", "chat gpt", "openai"],
        developer: "OpenAI",
        category: "Инструменты",
        rating: "4.7",
        reviewsCount: "2 млн",
        downloads: "100 млн +",
        size: "40.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/bnVHM-0sSrqrFl7dj2LIY7yl9z9X2jT0aOLKW7B2RdRpR4GRMO0VMmKvPBHLQw",
        description: "Официальное приложение ChatGPT от OpenAI. Интеллектуальный помощник для любых задач.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "claude": {
        title: "Claude: AI от Anthropic",
        aliases: ["claude", "клод", "anthropic"],
        developer: "Anthropic PBC",
        category: "Инструменты",
        rating: "4.6",
        reviewsCount: "500 тыс.",
        downloads: "50 млн +",
        size: "35.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/e5KnM3s6s0JqxXaORRO7HfV9_r7asmMBMLmzOLRQZUlQc2Xc5VqfQqAp4JGa5Rnkwl2",
        description: "Claude — мощный AI-ассистент от Anthropic для работы с текстом, кодом и сложными задачами.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "googlegemini": {
        title: "Gemini — чат-бот от Google",
        aliases: ["gemini", "гугл гемини", "google gemini", "гемини"],
        developer: "Google LLC",
        category: "Инструменты",
        rating: "4.5",
        reviewsCount: "800 тыс.",
        downloads: "100 млн +",
        size: "45.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/3JDE3H8VHO4RA9M02iSbHR0J9kkJIhFiDKVcYLnEfQNkJ8RxKhNBpFDhFmyvFpT4Cw",
        description: "Gemini — это AI-ассистент Google нового поколения с мощными возможностями генерации и анализа.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== TOOLS ==========
    "duolingo": {
        title: "Duolingo — учи языки",
        aliases: ["duolingo", "дуолинго", "дуо"],
        developer: "Duolingo",
        category: "Образование",
        rating: "4.7",
        reviewsCount: "10 млн",
        downloads: "500 млн +",
        size: "55.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/7OBMXxXRRVRhLe3j3U2UhFKr4LFEDQOUKLRaSFi6ZJZkmIxZvxhZ8LTG7rN2I0F9Qw",
        description: "Duolingo — самое популярное приложение для изучения иностранных языков. Более 40 языков!",
        screenshots: [],
        reviews: randReviews(4)
    },
    "strava": {
        title: "Strava: бег и велоспорт",
        aliases: ["strava", "страва"],
        developer: "Strava Inc.",
        category: "Приложения",
        rating: "4.5",
        reviewsCount: "3 млн",
        downloads: "100 млн +",
        size: "75.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/TKP7qCFJlZKz6nfzq3e6pxk6pCMvlHN7TbZxCm8aeajXXCnUON4WqoqT_kc5WPRA1M",
        description: "Strava — GPS-трекер для бега, велоспорта и других тренировок с социальными функциями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "paypal": {
        title: "PayPal: денежные переводы",
        aliases: ["paypal", "пэйпал", "пейпал"],
        developer: "PayPal Mobile",
        category: "Банки",
        rating: "4.1",
        reviewsCount: "5 млн",
        downloads: "500 млн +",
        size: "50.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/7aOF-3rrXcYnz88v5NG3a7-1iEuv4q7HGLqQcXH49hgDkX_Zv4yHqt7-G5V-mkQ5Y0",
        description: "PayPal — быстрые и безопасные денежные переводы онлайн по всему миру.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "revolut": {
        title: "Revolut: умный банк",
        aliases: ["revolut", "револют"],
        developer: "Revolut Ltd",
        category: "Банки",
        rating: "4.4",
        reviewsCount: "2 млн",
        downloads: "100 млн +",
        size: "60.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/qiNOhTWWNmqSKJBqH_MKb8KSE2N5DpW3yoOAjJ_I5R3A-D0RKIY3JaDv8UJCw9sFTg",
        description: "Revolut — финансовый суперапп: переводы в валюте, криптовалюта, акции и многое другое.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "uber": {
        title: "Uber: заказ такси",
        aliases: ["uber", "убер"],
        developer: "Uber Technologies, Inc.",
        category: "Приложения",
        rating: "4.3",
        reviewsCount: "15 млн",
        downloads: "500 млн +",
        size: "85.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/7j1j9DjBdN79s2bMm09fcSzPPbdCyKGBNyp8LFG6xLKhQfD_EKdN9sJBdpW0FxvxnMc",
        description: "Uber — заказывайте такси, еду, курьерскую доставку прямо с телефона.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "bolt": {
        title: "Bolt: такси и самокаты",
        aliases: ["bolt", "болт"],
        developer: "Bolt Technology OÜ",
        category: "Приложения",
        rating: "4.4",
        reviewsCount: "5 млн",
        downloads: "100 млн +",
        size: "60.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/HmL80wm2VZaJcimGzITLpQFZ3wBCTHHfYd1fVW60pPVZq95kJN2ydXCv2GGQL3fIvRA",
        description: "Bolt — удобное такси, самокаты, велосипеды и каршеринг по выгодным ценам.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "airbnb": {
        title: "Airbnb: жильё и путешествия",
        aliases: ["airbnb", "airbnb", "аирбнб", "эйрбнб"],
        developer: "Airbnb, Inc.",
        category: "Покупки",
        rating: "4.7",
        reviewsCount: "3 млн",
        downloads: "100 млн +",
        size: "70.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/AQtSF5Std5eR0wFiMZpUQqkJI_iqwSKIBVD8X5MFNbFjFJPexIr0S_m4JGKzHqGiAA",
        description: "Airbnb — бронируйте жильё, апартаменты и уникальные места для проживания по всему миру.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "booking": {
        title: "Booking.com: отели и жильё",
        aliases: ["booking", "бронирование", "букинг", "booking.com"],
        developer: "Booking.com",
        category: "Покупки",
        rating: "4.6",
        reviewsCount: "6 млн",
        downloads: "500 млн +",
        size: "65.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/fGFYETBkXwOhWkM7sFUx2yqhHJJLJL5igBxMN6J2TjJqLs_k0zyLZ3KXKF00OxeHpU",
        description: "Booking.com — бронируйте отели, апартаменты и дома по лучшим ценам без комиссии.",
        screenshots: [],
        reviews: randReviews(4)
    },

    // ========== CREATIVE TOOLS ==========
    "capcut": {
        title: "CapCut — видеоредактор",
        aliases: ["capcut", "кепкат", "капкат"],
        developer: "Bytedance Pte. Ltd",
        category: "Медиа",
        rating: "4.7",
        reviewsCount: "8 млн",
        downloads: "1 млрд +",
        size: "200.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/VCl4bKQmDlULT_LBv0GtbFxXyZ3Yx8lp6Z0RSmQnG_TqJHoiRH1jMVxl8VvCp9nCGNA",
        description: "CapCut — мощный и простой видеоредактор с AI-эффектами, фильтрами и шаблонами.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "canva": {
        title: "Canva: графический дизайн",
        aliases: ["canva", "канва"],
        developer: "Canva",
        category: "Инструменты",
        rating: "4.8",
        reviewsCount: "5 млн",
        downloads: "500 млн +",
        size: "80.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/F5e6bnWopZQg5gMgIU0-YRXkqMZf2G4sVKO4e2JR7KXF5B7mOPXDmBBB8bO4DYgLEg",
        description: "Canva — простой и мощный инструмент для создания дизайна: посты, плакаты, презентации.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "lightroom": {
        title: "Lightroom: редактор фото",
        aliases: ["lightroom", "лайтрум", "adobe lightroom"],
        developer: "Adobe Inc.",
        category: "Медиа",
        rating: "4.5",
        reviewsCount: "2 млн",
        downloads: "100 млн +",
        size: "90.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/fSfXq_n0JbC6P8aTzf0-6kXV8RFV6lchAGXGXRDvYaqiA0NEYJ-vbxZ6x_5zMMnhaw",
        description: "Adobe Lightroom — профессиональный редактор фотографий с расширенными инструментами цветокоррекции.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "photoshop": {
        title: "Adobe Photoshop",
        aliases: ["photoshop", "фотошоп", "adobe photoshop"],
        developer: "Adobe Inc.",
        category: "Медиа",
        rating: "4.3",
        reviewsCount: "1.5 млн",
        downloads: "50 млн +",
        size: "150.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/j4j9FxWqIyVZOA5K1V4sJv12c0l5VHq80U0tKBm_LkdHSzpT1N80UiWVYxd70VJ0oQ",
        description: "Adobe Photoshop — легендарный графический редактор для профессионального ретушу и дизайна.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== GAMES ==========
    "minecraft": {
        title: "Minecraft",
        aliases: ["minecraft", "майнкрафт"],
        developer: "Mojang",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "5 млн",
        downloads: "100 млн +",
        size: "157.0 MB",
        age: "7+",
        icon: "https://play-lh.googleusercontent.com/VSwHMHLD9sQK5mFUPMMDlWTha32rnIjfNbkEPV5e2b5EFU7RxGe6KfnfUOGm3n3h1g",
        description: "Minecraft — культовая игра-песочница, где вы строите, выживаете и создаёте свои миры.",
        screenshots: [],
        reviews: randReviews(5)
    },
    "stardewvalley": {
        title: "Stardew Valley",
        aliases: ["stardew", "stardew valley", "стардью"],
        developer: "ConcernedApe",
        category: "Игры",
        rating: "4.9",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "240.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/MHQ9yHKwQSP8ZCFUE-PVQXD1E26oFTa2l3hD4K2BDSzLiXRxZAi3XALcLHB-OzW4TY",
        description: "Stardew Valley — очаровательная ролевая игра-ферма. Стройте ферму, знакомьтесь с жителями деревни.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "terraria": {
        title: "Terraria",
        aliases: ["terraria", "террария"],
        developer: "505 Games Srl",
        category: "Игры",
        rating: "4.7",
        reviewsCount: "600 тыс.",
        downloads: "10 млн +",
        size: "195.0 MB",
        age: "7+",
        icon: "https://play-lh.googleusercontent.com/kq0GEqG6a-9pWpzMl1AHlG7TIFMg2g5wSO8m_P6D8Sg3GdPXi2jU1WM9gXwCFTblbA",
        description: "Terraria — двухмерная игра-песочница с исследованием, строительством и боёвкой.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "geometrydash": {
        title: "Geometry Dash",
        aliases: ["geometry dash", "геометри даш"],
        developer: "RobTop Games",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "2 млн",
        downloads: "100 млн +",
        size: "80.0 MB",
        age: "4+",
        icon: "https://play-lh.googleusercontent.com/jIbPb_T_HQ3sBNPUNF_jGJ-sUBs5O-y2DlI6_vShBFe2m4ZMVpX6B03uX-zV8PYsrA",
        description: "Geometry Dash — ритмическая платформенная игра с препятствиями под электронную музыку.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "plagueinc": {
        title: "Plague Inc.: Эволюция",
        aliases: ["plague inc", "plague", "плейг", "чума"],
        developer: "Ndemic Creations",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "1 млн",
        downloads: "100 млн +",
        size: "65.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/0HXNxbJlpfFhDCJnJWQ3mwMDnXa9B2x-_jV78K7TwHi_-9Eqh4JGF2IyLV4U64s3TQ",
        description: "Plague Inc. — стратегическая игра: заразите всё человечество уникальным патогеном!",
        screenshots: [],
        reviews: randReviews(3)
    },
    "bloonstd6": {
        title: "Bloons TD 6",
        aliases: ["bloons", "bloons td 6", "блунс"],
        developer: "Ninja Kiwi",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "1.5 млн",
        downloads: "50 млн +",
        size: "300.0 MB",
        age: "9+",
        icon: "https://play-lh.googleusercontent.com/vcpAyuTb2ZhXaWkjMT6MFh8LnqHWyE0RmCBJNWPNEI0KUUlYYJGEkh5QxcDNNOiRxCY",
        description: "Bloons TD 6 — лучшая игра в жанре Tower Defense с 50+ башнями, героями и обновлениями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "balatro": {
        title: "Balatro",
        aliases: ["balatro", "балатро"],
        developer: "LocalThunk",
        category: "Игры",
        rating: "4.9",
        reviewsCount: "200 тыс.",
        downloads: "5 млн +",
        size: "200.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/M6jCDHY9CfFHBbG_gIGmQ8-U5BvkJ3v_O6nAnkP7W1lTIhvfHkVf7WJ7hMXL5JLbpzQ",
        description: "Balatro — покерный рогалик с джокерами и безумными комбинациями. Игра 2024 года!",
        screenshots: [],
        reviews: randReviews(3)
    },
    "monopoly": {
        title: "MONOPOLY — классика",
        aliases: ["monopoly", "монополия"],
        developer: "Marmalade Game Studio",
        category: "Игры",
        rating: "4.2",
        reviewsCount: "1 млн",
        downloads: "10 млн +",
        size: "85.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/y5yzl_S-lHX5fMC4C08tJH73wfSnGYSEqiOm84dbtEWxc7O-jRa3FtaqZX0XYX_XBGE",
        description: "MONOPOLY — цифровая версия легендарной настольной игры с онлайн-мультиплеером.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "gtasanandreas": {
        title: "GTA: San Andreas",
        aliases: ["gta", "gta san andreas", "гта", "san andreas"],
        developer: "Rockstar Games",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "1.5 млн",
        downloads: "50 млн +",
        size: "2.5 GB",
        age: "17+",
        icon: "https://play-lh.googleusercontent.com/Tmo8WPPcTu9KGVIaOwVLX24m8dE5aUbQpFZFoM5AzGwt2gKjx7_HNpOz-M5ELW5x4Js",
        description: "GTA: San Andreas — легендарная криминальная игра в открытом мире на мобильных.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "wreckfest": {
        title: "Wreckfest",
        aliases: ["wreckfest", "рекфест"],
        developer: "HandyGames",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "100 тыс.",
        downloads: "1 млн +",
        size: "850.0 MB",
        age: "12+",
        icon: "https://play-lh.googleusercontent.com/zGzFhPH3mZhwDqCiPHPOinOmV4M8PrHH7yfVlMT6M2OqdnCiWqBZoFmkRxJ9cV75GHE",
        description: "Wreckfest — разрушительные автогонки с реалистичной физикой и суперграфикой.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "slaythespire": {
        title: "Slay the Spire",
        aliases: ["slay the spire", "слей зе шпайр"],
        developer: "Mega Crit",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "200 тыс.",
        downloads: "2 млн +",
        size: "300.0 MB",
        age: "9+",
        icon: "https://play-lh.googleusercontent.com/nqV0ZxjH8fGbXO9mq5WHANEpz-j8K6jHC8FgxCtNMfJLWEVeuwqaOo_lBG6PiHC5lg",
        description: "Slay the Spire — карточная рогалик-стратегия с бесконечными комбинациями и боссами.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "dontstarve": {
        title: "Don't Starve: Pocket Edition",
        aliases: ["dont starve", "don't starve", "донт старв"],
        developer: "Klei Entertainment",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "150 тыс.",
        downloads: "1 млн +",
        size: "500.0 MB",
        age: "9+",
        icon: "https://play-lh.googleusercontent.com/TJXKuAM65uiWpDMoLRhKKzX-j5-i0KF1mJOtQNTSVoAr_xdYE5bRJ7e-lY39fzl_y0",
        description: "Don't Starve — сюрреалистичная игра выживания в готическом стиле от Klei Entertainment.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "northgard": {
        title: "Northgard",
        aliases: ["northgard", "нортгард"],
        developer: "Shiro Unlimited",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "80 тыс.",
        downloads: "500 тыс. +",
        size: "700.0 MB",
        age: "7+",
        icon: "https://play-lh.googleusercontent.com/YhH-rAl7zyvLzP7nIj1O40iFzxXpU5H-kxRFSJKK7nHGjYKGM1vlHv-eIJy8XIVR6g",
        description: "Northgard — стратегия в сеттинге викингов: управляйте кланом, исследуйте и сражайтесь.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "deadcells": {
        title: "Dead Cells",
        aliases: ["dead cells", "дед селс"],
        developer: "Motion Twin",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "300 тыс.",
        downloads: "3 млн +",
        size: "400.0 MB",
        age: "16+",
        icon: "https://play-lh.googleusercontent.com/2fcXzWbzqxeJrJomO9z4Bqz4jIQRiYnMW3uHi9hk8r0m0VbECwUeImIIMj8zbnWh",
        description: "Dead Cells — брутальный рогалик-платформер с невероятной боёвкой и сотнями предметов.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "civilization6": {
        title: "Civilization VI: стратегия",
        aliases: ["civilization", "civ 6", "civilization vi", "цивилизация"],
        developer: "2K",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "200 тыс.",
        downloads: "1 млн +",
        size: "800.0 MB",
        age: "9+",
        icon: "https://play-lh.googleusercontent.com/9bZhCQBJ73Y-UgUU5CQ0MKRLS4BVi-FzXZ-KXMM9W6yFXy-QNMW1DRdnT1PN9ZWn4o",
        description: "Civilization VI — легендарная пошаговая стратегия. Постройте цивилизацию, которая переживёт века.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "divinityoriginalsin2": {
        title: "Divinity: Original Sin 2",
        aliases: ["divinity", "divinity original sin", "дивинити"],
        developer: "Larian Studios",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "100 тыс.",
        downloads: "500 тыс. +",
        size: "2.0 GB",
        age: "16+",
        icon: "https://play-lh.googleusercontent.com/1aJL0cEVRKF-lCKU08pTcOHGkAyRbLFjT6t_EBp1Yjp76oJlzVJlvPh90g5oKcG9fA",
        description: "Divinity: Original Sin 2 — шедевральная ролевая игра с пошаговыми боями и огромной свободой.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "kingdomtwocrowns": {
        title: "Kingdom Two Crowns",
        aliases: ["kingdom two crowns", "кингдом"],
        developer: "Raw Fury",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "80 тыс.",
        downloads: "500 тыс. +",
        size: "300.0 MB",
        age: "4+",
        icon: "https://play-lh.googleusercontent.com/V9SHCc97-X-gX-v3Eg9eGGJj_K3MU_C6XMD9oBCH72JK2AO1Gq9l0XsTt50_GE8QQ",
        description: "Kingdom Two Crowns — пиксельная стратегия о строительстве королевства и защите от орды грайдов.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "theescapists2": {
        title: "The Escapists 2",
        aliases: ["the escapists", "эскапистс", "escapists"],
        developer: "Team17 Digital Limited",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "60 тыс.",
        downloads: "500 тыс. +",
        size: "450.0 MB",
        age: "9+",
        icon: "https://play-lh.googleusercontent.com/cZhKWWMVq2oCZqjyJIWFr_UuRPMNlr3eBrfgJllJ_T3MwBH7bQjbGbM5hkQ4eVe72Q",
        description: "The Escapists 2 — придумайте хитрый план побега из тюрьмы, используя крафт и смекалку.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "thiswarofmine": {
        title: "This War of Mine",
        aliases: ["this war of mine", "эта война", "война"],
        developer: "11 bit studios",
        category: "Игры",
        rating: "4.6",
        reviewsCount: "100 тыс.",
        downloads: "1 млн +",
        size: "900.0 MB",
        age: "18+",
        icon: "https://play-lh.googleusercontent.com/nQFp4g8OHrh1y1x1aDEoJSrmxDQ4Y9XlB7a7a9XBl7FaWCFREGlrKGLiVjU6sKnaBX8",
        description: "This War of Mine — тяжёлая игра о выживании мирных жителей в условиях войны.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "monumentvalley": {
        title: "Monument Valley",
        aliases: ["monument valley", "монумент вэлли"],
        developer: "ustwo games",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "150.0 MB",
        age: "4+",
        icon: "https://play-lh.googleusercontent.com/HOJoYOEOAoAdUH9RhzaHxiL7f0ysomrBKFpLAW52lQ7V1NG2GDELhqGo4m7PqG9KxQ",
        description: "Monument Valley — завораживающая головоломка с невозможной архитектурой в духе Эшера.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "monumentvalley2": {
        title: "Monument Valley 2",
        aliases: ["monument valley 2", "монумент вэлли 2"],
        developer: "ustwo games",
        category: "Игры",
        rating: "4.8",
        reviewsCount: "250 тыс.",
        downloads: "5 млн +",
        size: "200.0 MB",
        age: "4+",
        icon: "https://play-lh.googleusercontent.com/AiX8Bq4UioJbwgf2dCg5DtM3iNkNlCmtCE7VaD0y5SjZP7cMMHV4lM0Yz-TiM2eQ4A",
        description: "Monument Valley 2 — продолжение культовой головоломки. Трогательная история матери и дочери.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "spongebob": {
        title: "SpongeBob SquarePants",
        aliases: ["spongebob", "спанч боб", "губка боб", "squarepants"],
        developer: "Nickelodeon",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "350.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/D4kpHl0m7g1N5J7OHZ_LjWx8YhFqLJ5cK3tMrVG1nYuXXI0LiWQ0wAY01l2TYhVMFg",
        description: "SpongeBob SquarePants: Battle for Bikini Bottom — приключения Спанч Боба в Бикини Боттом.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "farmingsimulator": {
        title: "Farming Simulator 23",
        aliases: ["farming simulator", "фермер", "farming", "симулятор фермы"],
        developer: "GIANTS Software",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "600.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/BjkJLHJSVB_k--D6JFHZ1c7OmX9GrH4FcJEAV7oWHSDtkyuN9kQGpbHQ4w8vWk_t4E",
        description: "Farming Simulator 23 — реалистичный симулятор фермы с сотнями машин и культур.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "oceanhorn": {
        title: "Oceanhorn: Monster of Uncharted Seas",
        aliases: ["oceanhorn", "оушенхорн"],
        developer: "FDG Entertainment",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "80 тыс.",
        downloads: "1 млн +",
        size: "650.0 MB",
        age: "7+",
        icon: "https://play-lh.googleusercontent.com/h-uG1EVRJ0T3oqfbpN4OxbFWzUd82OkjHjwAVfMFI-JniK0J8pBxXqQFQG5wdVCaA",
        description: "Oceanhorn — потрясающая приключенческая RPG в духе Legend of Zelda на мобильных устройствах.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== RUSSIAN BANKS ==========
    "sberbank": {
        title: "СберБанк Онлайн",
        aliases: ["sberbank", "сбер", "сбербанк", "сбербанк онлайн"],
        developer: "ПАО Сбербанк",
        category: "Банки",
        rating: "4.6",
        reviewsCount: "5 млн",
        downloads: "50 млн +",
        size: "88.0 MB",
        age: "3+",
        icon: "https://static.rustore.ru/imgproxy/rGr87NnjSOsiX-imht9uyNnHK-YDQJNvIlY2rIb4gsA/preset:web_app_icon_62/plain/https://static.rustore.ru/2026/5/6/2c/apk/312086/content/ICON/e5278a4b-b64f-4e96-bd39-c2c98609fc0c.png@webp",
        description: "СберБанк Онлайн — управляйте счетами, переводите деньги, оплачивайте услуги и многое другое.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "tbank": {
        title: "Т-Банк: дебетовые карты",
        aliases: ["tbank", "tinkoff", "тинькофф", "т-банк", "тинькофф банк"],
        developer: "АО ТБанк",
        category: "Банки",
        rating: "4.7",
        reviewsCount: "4 млн",
        downloads: "30 млн +",
        size: "60.0 MB",
        age: "3+",
        icon: "https://static.rustore.ru/imgproxy/B5vCiJBi9KIeZUhh3WS6X_5g7RuBMbOy_P88JdHoD1A/preset:web_app_icon_62/plain/https://static.rustore.ru/2026/7/26/8e/apk/313443/content/ICON/a1d50b5c-0f43-4a02-9a5e-e7cf91ed5abc.png@webp",
        description: "Т-Банк (Тинькофф) — банк в смартфоне с кэшбэком, вкладами и переводами.",
        screenshots: [],
        reviews: randReviews(4)
    },
    "vtb": {
        title: "ВТБ Онлайн",
        aliases: ["vtb", "втб", "втб онлайн"],
        developer: "Банк ВТБ (ПАО)",
        category: "Банки",
        rating: "4.5",
        reviewsCount: "1.5 млн",
        downloads: "10 млн +",
        size: "75.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/8UcEBhJO1LVGVdj-2wGYW3KzQNJhXIl2mVj1E-x9MjFMqfRidpW0kLhTQr1-nJjh0Q",
        description: "ВТБ Онлайн — полный контроль над финансами: платежи, переводы, инвестиции.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "alfabank": {
        title: "Альфа-Банк: Альфа-Онлайн",
        aliases: ["alfa", "alfabank", "альфа", "альфа-банк", "альфа банк"],
        developer: "АО «АЛЬФА-БАНК»",
        category: "Банки",
        rating: "4.6",
        reviewsCount: "2 млн",
        downloads: "20 млн +",
        size: "70.0 MB",
        age: "3+",
        icon: "https://static.rustore.ru/imgproxy/NW3cBQhLBT7cX5pRAa44d3KeRD8j0Baw3kUG3A_4WTs/preset:web_app_icon_62/plain/https://static.rustore.ru/2026/7/29/80/apk/336682/content/ICON/7c6e45d3-c75f-45af-9a19-05ef5e55d11d.png@webp",
        description: "Альфа-Банк — мобильный банк для управления картами, кредитами и инвестициями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "gazprombank": {
        title: "Газпромбанк: Финансы, Банк",
        aliases: ["gazprombank", "газпромбанк", "gpb"],
        developer: "Газпромбанк",
        category: "Банки",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "5 млн +",
        size: "65.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/Z1PeHBNBxS3Aqm7-BzwjBHGUFI-KGM8-cJxQy-QhHmcE0dCEf4tMV_TLvfRtPScXA",
        description: "Газпромбанк — управляйте своими финансами, переводами и платежами удобно и безопасно.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "rosselkhozbank": {
        title: "Россельхозбанк",
        aliases: ["rshb", "rosselkhozbank", "россельхозбанк", "рсхб"],
        developer: "Россельхозбанк",
        category: "Банки",
        rating: "4.2",
        reviewsCount: "200 тыс.",
        downloads: "2 млн +",
        size: "55.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/FW6jnSKi6rS5c8kFRB85Zap6xlqULvugjQ4aVkETi9e1rE2JyVN7g1cSh_Mxq-E2Mg",
        description: "Россельхозбанк — интернет-банк для физических лиц: платежи, переводы, депозиты.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "sovcombank": {
        title: "Совкомбанк — Деньги онлайн",
        aliases: ["sovcombank", "совкомбанк"],
        developer: "АО «Совкомбанк»",
        category: "Банки",
        rating: "4.3",
        reviewsCount: "250 тыс.",
        downloads: "2 млн +",
        size: "50.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/jKXfHblFQMWJDjOX9U9kVFNaW6mJBv9G0t3CX2_vHLv6OqNHpB0t2LVuD6N6VjJjHQ",
        description: "Совкомбанк — оформляйте карты и кредиты, совершайте платежи прямо в приложении.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "psb": {
        title: "Промсвязьбанк: ПСБ Банк",
        aliases: ["psb", "промсвязьбанк", "пром"],
        developer: "ПАО «Промсвязьбанк»",
        category: "Банки",
        rating: "4.3",
        reviewsCount: "200 тыс.",
        downloads: "3 млн +",
        size: "60.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/g3DMQF9Hj0MnOevpqHWKXqr4X49jxXfBKW9Q2jz29R5jJKtUOzTdxXoMFNPlXPJLw",
        description: "Промсвязьбанк — интернет-банк: переводы, оплата услуг, управление счетами.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "otkritie": {
        title: "Банк Открытие — Мой банк",
        aliases: ["otkritie", "открытие", "банк открытие"],
        developer: "ПАО Банк «ФК Открытие»",
        category: "Банки",
        rating: "4.2",
        reviewsCount: "150 тыс.",
        downloads: "1 млн +",
        size: "55.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/AKfqoMoSiW5mI4fFEAzpFvxW4GajNfT-zn9k4RMcPQ5FHdxs5fLhZCrF5A3mM48YBg",
        description: "Банк Открытие — дистанционный банкинг для физических лиц.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "raiffeisenbank": {
        title: "Райффайзен Онлайн",
        aliases: ["raiffeisen", "райффайзен", "raiffeisenbank"],
        developer: "АО «Райффайзенбанк»",
        category: "Банки",
        rating: "4.5",
        reviewsCount: "400 тыс.",
        downloads: "5 млн +",
        size: "70.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/TqJl6jz7GRHxcWe6z6t4LR1qW7Xl7yJG0mgjk5sHPHsV9R8SEvX9PFY4GkPX0FIwTA",
        description: "Райффайзен Онлайн — банк с широкими возможностями для переводов и платежей.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mkb": {
        title: "МКБ Мобайл",
        aliases: ["mkb", "мкб", "мкб мобайл", "московский кредитный банк"],
        developer: "ПАО «МКБ»",
        category: "Банки",
        rating: "4.3",
        reviewsCount: "100 тыс.",
        downloads: "1 млн +",
        size: "50.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/X_jT8DZP1u_rRpOVrb2UoaAvnk55fDmlyUFCEMbsXjJLhqXW4yFtj6w4jmKh6WJSOQ",
        description: "МКБ Мобайл — интернет-банкинг Московского Кредитного Банка.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "rosbank": {
        title: "Росбанк Онлайн",
        aliases: ["rosbank", "росбанк"],
        developer: "ПАО РОСБАНК",
        category: "Банки",
        rating: "4.2",
        reviewsCount: "120 тыс.",
        downloads: "1 млн +",
        size: "55.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/JxmW5fN-yWLR5n8J5mGR7GqPvRxSSNYqV3YuDuGbPJWFWtnM33jlCe4QrGbMb3sqMRU",
        description: "Росбанк Онлайн — удобное мобильное приложение для управления банковскими продуктами.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "uralsib": {
        title: "Уралсиб Банк Онлайн",
        aliases: ["uralsib", "уралсиб"],
        developer: "ПАО «БАНК УРАЛСИБ»",
        category: "Банки",
        rating: "4.1",
        reviewsCount: "80 тыс.",
        downloads: "500 тыс. +",
        size: "50.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/u_ioRgMlVMGXBqvsTlWF2fZCBJNQNEJP4f9GOmJJblfbAnC7aqCfNBJ5YenX28PkEA",
        description: "Уралсиб Банк Онлайн — переводы, платежи и управление продуктами банка в смартфоне.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "bankspb": {
        title: "Банк Санкт-Петербург",
        aliases: ["bank spb", "банк санкт-петербург", "бспб"],
        developer: "ПАО «Банк «Санкт-Петербург»",
        category: "Банки",
        rating: "4.2",
        reviewsCount: "70 тыс.",
        downloads: "500 тыс. +",
        size: "50.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/fQm0Rt1rBNFQ-6Lsyj0D62jD-WJI1lsKbPqoWdwn0tXRuQfZI9zSU2WlISMz3vGCA",
        description: "Банк Санкт-Петербург — интернет-банк для физических лиц.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "akbars": {
        title: "Ак Барс Банк",
        aliases: ["ak bars", "ак барс", "akbars"],
        developer: "ПАО «Ак Барс» Банк",
        category: "Банки",
        rating: "4.1",
        reviewsCount: "60 тыс.",
        downloads: "500 тыс. +",
        size: "48.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/Bji2EqCBJxmH8B5H0l71F4-B6Z8rCAj80r1Hpa1vifQ-Fy48i7UaULOvY3I5r8Uyg",
        description: "Ак Барс Банк — управление счетами, платежи и переводы онлайн.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "zenit": {
        title: "Зенит Онлайн",
        aliases: ["zenit", "зенит", "банк зенит"],
        developer: "Банк ЗЕНИТ",
        category: "Банки",
        rating: "4.0",
        reviewsCount: "30 тыс.",
        downloads: "200 тыс. +",
        size: "45.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/NVMxFWDqXlF75hDnJQRCvXFV7OfPcEZXWqS-zW7CKFGV3U0K0-gMvQpHbQZlGl0kA",
        description: "Зенит Онлайн — банковские операции в смартфоне: переводы, платежи, вклады.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "yumoney": {
        title: "ЮMoney — кошелёк и карта",
        aliases: ["yumoney", "ю мани", "юмани", "yandex money"],
        developer: "ООО НКО «ЮМани»",
        category: "Банки",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "40.0 MB",
        age: "3+",
        icon: "https://static.rustore.ru/imgproxy/F76HECvqdVJmS5M0u8rRV9Syo2MkxRwPVvGVfRkJNm4/preset:web_app_icon_62/plain/https://static.rustore.ru/2026/6/20/20/apk/5259174/content/ICON/e00a3da1-47a9-4b6b-b8ee-1d9a5ada7ff3.png@webp",
        description: "ЮMoney — электронный кошелёк Яндекса: пополнение, переводы, оплата онлайн.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "qiwi": {
        title: "QIWI: оплата и переводы",
        aliases: ["qiwi", "киви"],
        developer: "QIWI кошелёк",
        category: "Банки",
        rating: "4.2",
        reviewsCount: "1 млн",
        downloads: "10 млн +",
        size: "35.0 MB",
        age: "3+",
        icon: "https://play-lh.googleusercontent.com/GHXBZ12asSNFqjy1-k2FiWYPyvkXK7JXVSXhNhT0Z-bP3yMlT1gXBIFLpVlAMvX4A",
        description: "QIWI — моментальные платежи, переводы и удобный электронный кошелёк.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mirpay": {
        title: "Мир Pay",
        aliases: ["mir pay", "мир пей", "mirpay"],
        developer: "НСПК",
        category: "Банки",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "30.0 MB",
        age: "3+",
        icon: "https://static.rustore.ru/imgproxy/w2pjHEXI3EjGHCJNzYJJLHqK_gI2MLXLxSiCRwcfDNQ/preset:web_app_icon_62/plain/https://static.rustore.ru/2026/3/17/0b/apk/336843/content/ICON/02c61e28-c0b4-4e84-8d50-2e95dae5d98f.png@webp",
        description: "Мир Pay — платёжный сервис для оплаты картами платёжной системы Мир через смартфон.",
        screenshots: [],
        reviews: randReviews(3)
    },

    // ========== KIDS APPS ==========
    "tocabocarworld": {
        title: "Toca Boca World",
        aliases: ["toca boca world", "toca boca", "тока бока", "тока бока ворлд"],
        developer: "Toca Boca AB",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "3 млн",
        downloads: "100 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/Qxu5xfPqFfXQFrk0Aw5JZ0y1KTuVkpbsj45smGaxFCJQkH_UGtMbVlHlU9oMvKr4FI",
        description: "Toca Boca World — огромный игровой мир с персонажами и локациями без рекламы и покупок.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "tocalifework": {
        title: "Toca Life: World",
        aliases: ["toca life world", "toca life", "тока лайф"],
        developer: "Toca Boca AB",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "2 млн",
        downloads: "50 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/kMbcUCIKcJQVB_p6s0qg4j2P9FN0O7HwMNqU3yQLlcYr7K5ZbZ7wS3k2KqCKRMUAXA",
        description: "Toca Life: World — создай свой мир и придумывай истории вместе с героями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "migatownworld": {
        title: "Miga Town: My World",
        aliases: ["miga town", "miga", "мига таун", "miga town my world"],
        developer: "Miga Town",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "1 млн",
        downloads: "50 млн +",
        size: "150.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/yBaGGvKp24CYmxZlNyGFwipRVz4KIYhc0WZlPpHtjfmH9ORbJDh-i7DW2P4YmPt0rA",
        description: "Miga Town: My World — детская игра с открытым миром, полным приключений.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "migatownpets": {
        title: "Miga Town: My Pets",
        aliases: ["miga pets", "miga town pets", "мига питомцы"],
        developer: "Miga Town",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "120.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/z1h2Pf0TvGQjbVRxE_zIhMYRMCxS1D4s_4-KqGOFgfVhUOj-xFkPEL-Uw0sOhMuHhg",
        description: "Miga Town: My Pets — ухаживайте за милыми питомцами в весёлой детской игре.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "migatownvacation": {
        title: "Miga Town: My Vacation",
        aliases: ["miga vacation", "miga town vacation"],
        developer: "Miga Town",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "130.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/hRiZlRBmqlHTQ9Ec2d7v8Bz_UBzr4HiazE8kX7_NZEH1c-iFJvS_8VmLi8Xb1gMrA",
        description: "Miga Town: My Vacation — отправьтесь в увлекательный отпуск вместе с любимыми персонажами.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "migatownschool": {
        title: "Miga Town: My School",
        aliases: ["miga school", "miga town school"],
        developer: "Miga Town",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "120.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/8R0fX4xS-v1UKJZi0-rMOw9Oi-bq2cJzDG_cPJSw7BBMT8GI5T5L4vEhGcEY2R5YA",
        description: "Miga Town: My School — исследуй школу, заводи друзей и учись в игровой форме.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "drpandatown": {
        title: "Dr. Panda Town",
        aliases: ["dr panda", "dr. panda town", "доктор панда"],
        developer: "Dr. Panda Ltd",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "600 тыс.",
        downloads: "10 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/0hHXkNLNlD9nCAWs_KVUm4vHX5IZVbFAo2V14Ixwq6DEmJ6cFJ-dJA52w1DWAXgvVw",
        description: "Dr. Panda Town — детская игра для изучения мира через ролевые игры в виртуальном городе.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "drpandatowntales": {
        title: "Dr. Panda Town Tales",
        aliases: ["dr panda tales", "dr. panda town tales"],
        developer: "Dr. Panda Ltd",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "250.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/6FqCpHmhJiMjFuRqBBz4E6PGpCWI6d_R7JZ-Sp7xXfKF6HCCL30DUTjnj1ZS2tVww",
        description: "Dr. Panda Town Tales — истории и приключения в весёлом городе от Dr. Panda.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "pepihouse": {
        title: "Pepi House: Happy Family",
        aliases: ["pepi house", "пепи хаус"],
        developer: "Pepi Play",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "150.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/gKA0PsFBiG9APeP9V1eJ5bqH5Kl4lMJ-3TA-cL97VeG_-b8BpMqV7Tm4e8r-L9ZATA",
        description: "Pepi House — игра для детей о жизни счастливой семьи в уютном доме.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "pepisuperstores": {
        title: "Pepi Super Stores",
        aliases: ["pepi super stores", "пепи магазин"],
        developer: "Pepi Play",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "150.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/MpTJfTFjqJN4W8hOV3C9i7-LZ6V6kFJGwL4gX5_SdYIqxrlfBEqnY8l4fEzmWOl1jQ",
        description: "Pepi Super Stores — детская игра о работе в большом торговом центре.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "pepiwonderworld": {
        title: "Pepi Wonder World",
        aliases: ["pepi wonder world", "pepi wonder"],
        developer: "Pepi Play",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/Y4OqFaVgI7Xqf_pVYrYR6K5SFqXm8eOqbIqh9V7cOgzGBnfxfTl6UGXevdz8mOV_A",
        description: "Pepi Wonder World — волшебный мир приключений и фантазий для маленьких детей.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "pepihospital": {
        title: "Pepi Hospital",
        aliases: ["pepi hospital", "пепи больница"],
        developer: "Pepi Play",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "160.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/4tNj-Z7kMk3Z2q3_G0cW7xwT3S8HYU5B-Rp-CQXWY-s7g8fgLhLX27ARLKhx5_hqg",
        description: "Pepi Hospital — стань доктором и помогай пациентам в весёлой детской больнице.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "sagominiworld": {
        title: "Sago Mini World",
        aliases: ["sago mini world", "sago mini", "саго мини"],
        developer: "Sago Mini",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "600 тыс.",
        downloads: "10 млн +",
        size: "250.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/VhJ1w9_f9TqEFQnL9HO5W6fBnGp9m0Z-4r0ZYcKKlHQ_B3C1VlFMrQ_fzYAD5kQKYg",
        description: "Sago Mini World — тихие и добрые игры для самых маленьких: 40+ мини-игр.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "sagominischool": {
        title: "Sago Mini School",
        aliases: ["sago mini school", "sago school"],
        developer: "Sago Mini",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/gxAo9MNBHNxCk6OdlHE0H-y9yvNl0_kHf8hpZQA3yC5rMOExEF6-MDqdY3q4ZQRW5A",
        description: "Sago Mini School — маленькие уроки для дошкольников в игровом формате.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "sagominibigcity": {
        title: "Sago Mini Big City",
        aliases: ["sago mini big city", "sago city"],
        developer: "Sago Mini",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/kHZbJPtD8hAJrHAzM5HcHnk_VuATpS_2e6kS4tqVNBMjCd-kbQJgJ9tTq7HKGb3xaw",
        description: "Sago Mini Big City — исследуй большой город вместе с Харви Псом и его друзьями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "avatarworld": {
        title: "Avatar World: City Life",
        aliases: ["avatar world", "аватар ворлд"],
        developer: "Pazu Games",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "800 тыс.",
        downloads: "20 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/dGRpP1B8CqYp8-8RMFxYr9s1KKxMmVwsOEg4W7sifPO98QrBk7IpYCFBJjBqPqbwjg",
        description: "Avatar World — создай своего персонажа и живи в ярком виртуальном городе.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "avatarworldcitylife": {
        title: "Avatar World: Bff City Life",
        aliases: ["avatar world city life", "avatar city life"],
        developer: "Pazu Games",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/mItWE-V7Xr5WbRkK2jSRiT7QdPyuV-W5eE9Kc9Gv3Mzb59ZPJy6H8_6_CuTnFBMuw",
        description: "Avatar World: City Life — жизнь в городе с лучшим другом: мода, дом и приключения.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "moy7": {
        title: "Мой виртуальный питомец Мой 7",
        aliases: ["moy 7", "moy7", "мой 7"],
        developer: "Frojo Apps",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "100.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/SaxgG_wvJmnnphb4uT7_JXqq6Oz_2E6v9J3pqSH62YcFNGZ1oqLqWFkO3bLtfvIqzQ",
        description: "Мой 7 — заботьтесь о виртуальном питомце Мой: кормите, играйте и одевайте!",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycitylondon": {
        title: "My City : London",
        aliases: ["my city london", "мой город лондон"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/yJj7nRlLn8FyP8OAq-bHpz_u3T9Gj3JaT2NHZtB7V7_G2D7u2nv7bYuTQVHr-lJAQ",
        description: "My City: London — исследуй Лондон, примеряй разные роли и создавай свои истории.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycityparis": {
        title: "My City : Paris",
        aliases: ["my city paris", "мой город париж"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "350 тыс.",
        downloads: "10 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/qQ0LQ6gEH1oI5aN8Gp5aKREhEBt1SoBxW0pDLqZTb0hFwVo7Aa7SzXvqY4m2N9kOcg",
        description: "My City: Paris — прогулки по Парижу, разные профессии и приключения для детей.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycitynewyork": {
        title: "My City : New York",
        aliases: ["my city new york", "мой город нью-йорк"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/YnxzLO95Dh1Mxm6s9Nop7MV9eMTTBRPfV-j_bNqxLZAtBqj8fM9xJYJxeFNdh3ZkQ",
        description: "My City: New York — жизнь в Нью-Йорке: такси, небоскрёбы и настоящий городской ритм.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycityboatadventure": {
        title: "My City : Boat Adventure",
        aliases: ["my city boat adventure", "my city boat"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "250 тыс.",
        downloads: "5 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/TlLwPNK3VH2XZpV9M4dlOKY0eRuBQjuvRbk-fgBbWEOb_BpJ3nluMa0gRMqfGhlRAA",
        description: "My City: Boat Adventure — морские приключения на яхте с семьёй и друзьями.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycityhome": {
        title: "My City : Home",
        aliases: ["my city home", "мой дом"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "600 тыс.",
        downloads: "20 млн +",
        size: "170.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/r3bORwGtX3JJ5Q9mmKtWJj8JBf6vhHPOvX7j1vMDFMUqJhz9yqzR8VcMc-P4_0HxbQ",
        description: "My City: Home — обустраивайте дом и живите вместе с семьёй в уютной игре.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mycitymansion": {
        title: "My City : Mansion",
        aliases: ["my city mansion", "особняк"],
        developer: "My City Entertainment Ltd",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "300 тыс.",
        downloads: "5 млн +",
        size: "180.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/i1DJtlJ0eJjGt7h3V_L00TJicLW9y5Pr_BqMaFq50zy9OjCXGd6Wq5M18_RGEaL2ew",
        description: "My City: Mansion — живи в роскошном особняке и устраивай вечеринки.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mytownhome": {
        title: "My Town : Home Dollhouse",
        aliases: ["my town home", "my town", "мой таун дом"],
        developer: "My Town Games LTD",
        category: "Игры",
        rating: "4.5",
        reviewsCount: "1 млн",
        downloads: "50 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/JgRHzaCyWGflzNmqSmQVOVwg-Q0kOkRMcMQY1iAq_oHZ2Yxep4U5bEEOoSKmJa6nrQ",
        description: "My Town: Home — кукольный дом с множеством комнат и персонажей для ролевых игр.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mytownbestfriends": {
        title: "My Town : Best Friends' House",
        aliases: ["my town best friends", "best friends house"],
        developer: "My Town Games LTD",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/u9f7i6yY0tDwP8sW5sE0-mLIYlXmUXeW0LlH8PdDmSYfVe8lLi_V9oQqXC4rlEMFcg",
        description: "My Town: Best Friends' House — навещайте лучшего друга и устраивайте веселые игры.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mytownschool": {
        title: "My Town : School",
        aliases: ["my town school", "мой таун школа"],
        developer: "My Town Games LTD",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "600 тыс.",
        downloads: "20 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/UMy8WR4yVZ4P4V7yVHhE2j1P4JxOH2H7xb2D3eLJKPnGU3kAWYO8H3iRQx9V0VkVCQ",
        description: "My Town: School — учёба, переменки и дружба в весёлой школе.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mytownairport": {
        title: "My Town : Airport",
        aliases: ["my town airport", "мой таун аэропорт"],
        developer: "My Town Games LTD",
        category: "Игры",
        rating: "4.4",
        reviewsCount: "500 тыс.",
        downloads: "10 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/fkjq4ZcTQPmRR5M3-1YhSq4tYJLrNkz0-k-BbKSqmGrfX3_Mw0KjFhU-lJ2AQ-YXRQ",
        description: "My Town: Airport — жизнь в аэропорту: пилоты, пассажиры и множество самолётов.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "mytownhotel": {
        title: "My Town : Hotel",
        aliases: ["my town hotel", "мой таун отель"],
        developer: "My Town Games LTD",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "400 тыс.",
        downloads: "10 млн +",
        size: "200.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/6CZRyLbE7JG3-2JWqeWBECBlJVQ_XMNhU6m8m0-JXFjJBKHuCc03TiU7-jE2kMcr4Q",
        description: "My Town: Hotel — управляй фешенебельным отелем и принимай гостей.",
        screenshots: [],
        reviews: randReviews(3)
    },
    "cupcat": {
        title: "CupCat",
        aliases: ["cupcat", "кап кэт", "капкет"],
        developer: "CupCat Games",
        category: "Игры",
        rating: "4.3",
        reviewsCount: "200 тыс.",
        downloads: "1 млн +",
        size: "100.0 MB",
        age: "0+",
        icon: "https://play-lh.googleusercontent.com/M7y6JRpg7B5hc6x5MfPJx3sxMoP7-JktKJ3Xl9pCa4fVvMg8YevnN4LTB1RkMibEQ",
        description: "CupCat — милая игра про котика в чашечке, полная приключений и мини-игр.",
        screenshots: [],
        reviews: randReviews(3)
    }
};

// Load existing data.js, inject new entries
let dataContent = fs.readFileSync('data.js', 'utf8');

// Find the end of the appsData object (before the closing };)
const insertPoint = dataContent.lastIndexOf('\n};');

if (insertPoint === -1) {
    console.error('Could not find insertion point');
    process.exit(1);
}

// Build injection string
let injection = '';
for (const [key, app] of Object.entries(newApps)) {
    injection += `,\n    "${key}": ${JSON.stringify(app, null, 8).replace(/^/gm, '    ').trim().replace(/^    /, '')}`;
}

// Fix indentation (remove extra leading spaces from JSON.stringify output)
injection = injection.replace(/^    /gm, '    ');

const newContent = dataContent.slice(0, insertPoint) + injection + '\n' + dataContent.slice(insertPoint);
fs.writeFileSync('data.js', newContent);

// Also update data.json if it exists
if (fs.existsSync('data.json')) {
    let json;
    try { json = JSON.parse(fs.readFileSync('data.json', 'utf8')); } catch(e) { json = {}; }
    for (const [key, app] of Object.entries(newApps)) {
        json[key] = { ...app, reviews: [] };
    }
    fs.writeFileSync('data.json', JSON.stringify(json, null, 4));
}

// Bump versions in HTML files
['index.html', 'app.html'].forEach(f => {
    let c = fs.readFileSync(f, 'utf8');
    c = c.replace(/data\.js\?v=\d+/g, 'data.js?v=1005');
    c = c.replace(/search\.js\?v=\d+/g, 'search.js?v=1005');
    fs.writeFileSync(f, c);
});

console.log(`✅ Added ${Object.keys(newApps).length} apps to data.js`);
